services:
  webapi:
    build:
      context: .
      dockerfile: Projeto.Renda.Variavel.WebApi/Dockerfile
    container_name: renda-variavel-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;user=root;password=root;database=renda_variavel
      - Kafka__BootstrapServers=kafka:9092
      - Serilog__WriteTo__2__Args__serverUrl=http://seq
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Quotes.Consumer/Dockerfile
    container_name: quotes-consumer
    depends_on:
      - kafka
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__Topic=quotes-topic
      - Serilog__WriteTo__2__Args__serverUrl=http://seq
    networks:
      - app-network

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: renda_variavel
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
